name: secret-santa-draws
region: nyc
services:
  - name: web
    github:
      repo: ngenest/SecretSanta
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
