export const STRIPE_PUBLISHABLE_KEY =
  import.meta.env.VITE_STRIPE_PUBLISHABLE_KEY ||
  'pk_live_51SRxxNLvMBtfThSo1fJbRfEeS4asHZotFDzwLxWBOnHiB0yuQ0w125x3P5ZTFgeBG9Mj9m6NuTtwAVa4Cjs0na1R00OHQ6Q45j';

export const NOTIFICATION_PAYMENT_AMOUNT_CENTS = 199;
export const NOTIFICATION_PAYMENT_CURRENCY = 'usd';
